---
commit_boost_network: 'hoodi'
commit_boost_relays:
  - id: 'flashbots'
    url: 'https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-hoodi.flashbots.net'
  - id: 'titan'
    url: 'https://0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f@hoodi.titanrelay.xyz'
  - id: 'aestus'
    url: 'https://0x98f0ef62f00780cf8eb06701a7d22725b9437d4768bb19b363e882ae87129945ec206ec2dc16933f31d983f8225772b6@hoodi.aestus.live'
  - id: 'blxrbdn'
    url: 'https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.hoodi.blxrbdn.com'
commit_boost_cont_port: 18550

# Default is 2000ms, since this node has 2660 validators there is a delay within VC
commit_boost_late_in_slot_time_ms: 2500

beacon_node_payload_builder_url: 'http://localhost:{{ commit_boost_cont_port }}'

open_ports_list:
  commit-boost:
    - { port: '{{ commit_boost_cont_metrics_port }}', comment: 'Commit Boost metrics', ipset: 'hq.metrics', iifname: 'wg0' }