---
# Communityu test REST API endpoint.
beacon_node_rest_address: '0.0.0.0'

# WARNING: This will change if number of nodes changes.
redirect_ports:
  # beacon-node-prater-unstable-02
  - { src: 80, dst: 9305, comment: 'Test Beacon API (80->9304/tcp)' }
