---
# Add volume for Nimbus data
bootstrap__extra_volume_path: '/docker'

# TRACE needs more disk space
bootstrap__rsyslog_docker_logs_path: '/docker/log'
# lower local retention to save space
bootstrap__logrotate_frequency: 'hourly'
bootstrap__logrotate_count: 3
bootstrap__logrotate_mbytes: 500

# temporary
beacon_node_log_level: TRACE
# resource limits
beacon_node_cpu_limit: 0.25
beacon_node_mem_limit: '{{ (ansible_memtotal_mb * 0.20) | int }}'
beacon_node_cpu_reserve: 0.20
beacon_node_mem_reserve: '{{ (ansible_memtotal_mb * 0.1) | int }}'
