---
# Go-Ethereum
geth_service_name: 'geth-kiln-{{ "%02d"|format(idx|int+1) }}'
geth_network_id: 1337802
geth_sync_mode: 'snap'
geth_log_level_name: info
# Container
geth_cont_tag: 'merge-kiln-v2'
geth_cont_image: 'statusteam/go-client:{{ geth_cont_tag }}'
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
# Memory settings
geth_cont_mem_ratio: 0.3
# Genesis
geth_init_enabled: true
geth_init_url: 'https://config.kiln.themerge.dev/el/genesis/geth.json'
geth_init_sha256: 'f77edfa0fd6bfa787961f994abeacb521d6a63e895a04fcb8498f0adb971fb4b'
# Bootsrap
geth_bootnodes:
  - 'enode://c354db99124f0faf677ff0e75c3cbbd568b2febc186af664e0c51ac435609badedc67a18a63adb64dacc1780a28dcefebfc29b83fd1a3f4aa3c0eb161364cf94@164.92.130.5:30303'
  - 'enode://d41af1662434cad0a88fe3c7c92375ec5719f4516ab6d8cb9695e0e2e815382c767038e72c224e04040885157da47422f756c040a9072676c6e35c5b1a383cce@138.68.66.103:30303'
  - 'enode://91a745c3fb069f6b99cad10b75c463d527711b106b622756e9ef9f12d2631b6cb885f831d1c8731b9bc7177cae5e1ea1f1be087f86d7d30b590a91f22bc041b0@165.232.180.230:30303'
  - 'enode://b74bd2e8a9f0c53f0c93bcce80818f2f19439fd807af5c7fbc3efb10130c6ee08be8f3aaec7dc0a057ad7b2a809c8f34dc62431e9b6954b07a6548cc59867884@164.92.140.200:30303'
# Enable engine API
geth_rcp_api: 'eth,net,web3,personal,admin,engine'
geth_websocket_api: 'eth,net,web3,personal,admin,engine'
# Ports
geth_port: '{{ 30303 + idx|int + 1 }}'
geth_metrics_port: '{{ 6060 + idx|int + 1 }}'
geth_rpc_enabled: true
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: '{{ 8545 + idx|int + 1 }}'
geth_websocket_enabled: true
geth_websocket_addr: '0.0.0.0'
geth_websocket_port: '{{ 9546 + idx|int + 1 }}'

# Beacon Nodes
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-devauth-{{ "%02d"|format(idx|int+1) }}'
beacon_node_network: 'kiln'
beacon_node_proposer_boosting_debug: true
# FIXME: Pinned because bf127920 breaks the testnet config.
beacon_node_repo_branch: 'a35c5f83a8f7880165e19784f73463663db9fdd8'
# Builds
beacon_node_build_frequency: 'daily'
# Eth1 Sync
beacon_node_web3_urls: ['ws://{{ hostname }}.wg:{{ geth_websocket_port }}']
# Validators from nimbus-private repo
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_listening_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_metrics_port:   '{{ 9200 + idx|int + 1 }}'
beacon_node_rest_port:      '{{ 9300 + idx|int + 1 }}'
beacon_node_rpc_port:       '{{ 9900 + idx|int + 1 }}'

nodes_layout:
  'metal-01.he-eu-hel1.nimbus.kiln':
    - { start:   0, end: 125 }
    - { start: 125, end: 250 }
    - { start: 250, end: 375 }
    - { start: 375, end: 500 }
