---
# TRACE needs more disk space
bootstrap__rsyslog_docker_logs_path: '/docker/log'
# The volume of logs is too big and Nimbus team doesn't use their own cluster
bootstrap__rsyslog_docker_logstash_send: false

# lower local retention to save space
bootstrap__logrotate_frequency: 'hourly'
bootstrap__logrotate_count: 3
bootstrap__logrotate_mbytes: 500

# temporary
beacon_node_log_level: TRACE
# resource limits
beacon_node_mem_limit: '{{ (ansible_memtotal_mb * 0.60) | int }}'
beacon_node_mem_reserve: '{{ (ansible_memtotal_mb * 0.4) | int }}'
