---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: 60587f86e085255b537cc37647003af105214d20
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 50eda0808cceaaad2a5c5cdb4493935f2e3a637d
  scm: git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git
  version: fb631ec6b51d3cfb45c8373486bb9cdfb2073f37
  scm: git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git
  version: cc1e959b97dfe3320d5a17ec5b9bb888546c6500
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: b711bbabd2dc3d9ce8b1c3a6e5bc785901db9d09
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: b551ae21261775bd68ba59af0ccb8b11dcef962e
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 0cddfb4dd696e759a0a95c4753e7b95aeedc4242
  scm: git

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: a573ab89f2a75a7c80ba98e254b26644b9eb2fb2
  scm: git

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: f7b8578873dff723784aca9bd550f1f0dc32a9c1
  scm: git

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: 159f8e6bf078e33a7901ba03c7c4225093e23d86
  scm: git

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 3a1a651d92f7533b974ad74e69956fb815bd9fbe
  scm: git

- name: infra-role-nimbus-fluffy
  src: git@github.com:status-im/infra-role-nimbus-fluffy.git
  version: 0f54a4df9fae2868c49b92ce2a2e4a0cb6ab2a4b
  scm: git

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: 99a6a191c2e16206bb15c1c461411b85caae015b
  scm: git

- name: infra-role-rocketpool
  src: git@github.com:status-im/infra-role-rocketpool.git
  version: 09b4ab49a1c234185294443507495ebb32393e54
  scm: git

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 2f89ee1ffac7d678ed25b63a718b1018e1ec860f
  scm: git

- name: kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: 8e8c89b6999883b7558ce543108882a09b0d51ab
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 0677d8a98721b451f3d44f9827f05bfd880cfd1d
  scm: git

- name: elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: ba77cb2660870eb84f103b30f2f10661b8429cb9
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: c6bbc3d1b4b0ba603d82fa06cd17297d12523182
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 3de59d6ae76b69291905d16c264a1d11a5e2e955
  scm: git

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 30e6a08e9b2badffbd32472fff640aefef26fd37
  scm: git

- name: infra-role-openethereum
  src: git@github.com:status-im/infra-role-openethereum.git
  version: ddcac93d54dbb04fe6a971e7c1d1817cfe7b2b10
  scm: git
