---
- name: nginx
  src: git@github.com:status-im/ansible-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f7dcb7e1944d2ec0655bf8e7ce6f45a1317b65b9
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 54125c7d291289aaea51ca313fc694d057d803fa
  scm: git

- name: infra-role-bootstrap
  src: git@github.com:status-im/infra-role-bootstrap.git
  version: c1f535e4b2851f08b1013bd57ab42d0c1e31e3b2
  scm: git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap.git
  version: eb6400281bd3183733691344191bd53b2eceaa49
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: 567b4cf59d97f87be78e77e62684214f6de03096
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 87f4498f90f0cbb66a1ddb425e8953b04ced1891
  scm: git

- name: infra-role-beacon-node
  src: git@github.com:status-im/infra-role-beacon-node.git
  version: a14c9afe0293196f8b3cb45e86abcbaee3078d77
  scm: git

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: e69cebc8bd6bd5bf7f0cc1bb9ebd48a05cb31298
  scm: git

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: 1809e84d48d31cac0b783ed3a2182fdd23e34779
  scm: git

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 9c1584c1b23d9fcb99672fdbff472271acb324a7
  scm: git

- name: kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: 6c170c45c8776fcd1f9cef2274488519245cd35b
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 21a90e184941a708fd6c7386ac7ec2f365286f24
  scm: git

- name: elasticsearch-hq
  src: git@github.com:status-im/infra-role-elasticsearch-hq.git
  version: a92df1ac36c9a8e86fabefb54e24fe33d572ce10
  scm: git

- name: elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: 7a6018c791690f2ed3e07a9d44319846b6e76b6d
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: 5eafd38e4374f56a3439232b72ec077d569e0f5c
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 7b27e0f75aac29800c6d1a51a5f38ae7d2390aab
  scm: git

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 30e6a08e9b2badffbd32472fff640aefef26fd37
  scm: git
