- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git

- name: infra-role-nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 285cc7aba6144571a2084d9eb06745700e065e18

- name: infra-role-origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f2b061da8976444d6576b755578f0e799cde4372

- name: infra-role-oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: 49aeb3918b2c0d058af71d58b6d62118d6eebbaa

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 1c66555b67d4172aa8d2218478464c9dc9be77ab

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: 901710419177efb6e7dd84b742f8c0f8e6794c34

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: 6f36158d9f4e91b8d4f81ce28c31f358d760e77b

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: f754e9f51e19063798a754fa1f45e6518425a99f

- name: infra-role-validator-client
  src: git@github.com:status-im/infra-role-validator-client.git
  version: 89a89edd1e442247cb2391c309e6750b679f55b1

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 8b6730515780ee3ee721c4d30987a08aa211f027

- name: infra-role-nimbus-portal-client
  src: git@github.com:status-im/infra-role-nimbus-portal-client.git
  version: d2862a11f33edfe4cac681fb0d666c9db728a600

- name: infra-role-portal-bridge
  src: git@github.com:status-im/infra-role-portal-bridge.git
  version: ecdea0bf194c2b771f46d02cff3972a20801cb44

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: e3a4c34ebe4f1eeb95ad8d692b1ae25ea454cf99

- name: infra-role-rocketpool
  src: git@github.com:status-im/infra-role-rocketpool.git
  version: 6ea837b625093059d9a9e2aa92465f7c6e7b8f42

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 93c8a5b5ac091a128efe937c028b548751295297

- name: infra-role-kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: 11438c28906078ff8d47563b169926b5c2a89b96

- name: infra-role-elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 32b5b1b7e89d49c52567ad75504b325fed92f6a4

- name: infra-role-elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: 6297f24c6fc59aa09e1b8bf58c8391f9a792c7e1

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: c69efc1765ea8da664494feda207d57a63687f9a

- name: infra-role-launchd-timer
  src: git@github.com:status-im/infra-role-launchd-timer.git
  version: b594894f84fd48ef7d64a306ffaffcb6ae8495f5

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 20125d6e857d7e6ac874913360e7da0fe7c806a3

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 0859bd5b4a5010a7377c01ea3b4bb26195a594f4

- name: infra-role-erigon
  src: git@github.com:status-im/infra-role-erigon.git
  version: 837182ba87d5f99d4909b50f82f1a7ca75be4f1f

- name: infra-role-nethermind
  src: git@github.com:status-im/infra-role-nethermind.git
  version: 5b7c8a455e75c58884aba8b5b34de25253501c4b

- name: infra-role-smart-metrics
  src: git@github.com:status-im/infra-role-smart-metrics.git
  version: 9816b7aeaa1a05bb20b3ffb47a05b42850821e08

- name: infra-role-mev-boost
  src: git@github.com:status-im/infra-role-mev-boost.git
  version: d9cc07efeb4787422a36e0541273bd5324675e41

- name: infra-role-nimbus-bench-eth1
  src: git@github.com:status-im/infra-role-nimbus-bench-eth1.git
  version: b7769b993243c06139a71d69ba3c7c608562460b

- name: infra-role-nimbus-light-client
  src: git@github.com:status-im/infra-role-nimbus-light-client.git
  version: e1b14d67ddb040e59e004780b6b9cf7d4428a04b

- name: infra-role-rpc-snooper
  src: git@github.com:status-im/infra-role-rpc-snooper.git
  version: 1147652034e759439347c2f4a24c8bdbb6f08b5c

- name: infra-role-obol-charon
  src: git@github.com:status-im/infra-role-obol-charon.git
  version: 9d47eab7499bd75fbcb3a87ceb8ed1ec6e09fd9c

- name: infra-role-aztec
  src: git@github.com:status-im/infra-role-aztec.git
  version: 40d02706280c8f225720fd3bfd7052a3e1f234e9

- name: infra-role-commit-boost
  src: git@github.com:status-im/infra-role-commit-boost.git
  version: ed5b987cbe144728ba77a429b8ca5c02b7ed16fc
